### ISSUE TITLE
bcm2835-bootfiles missing  in case of zImage

### ISSUE THREAD

**Issue by embeddedgeeks** [djwillis/meta-raspberrypi#100]
it's a bit wierd but in case of KERNEL_IMAGETYPE set to zImage the bcm2835-bootfiles are missing in the sdcard image !

**Comment by agherzan** [comment]
Could you please create a card in https://trello.com/b/QsYeVjVe/meta-raspberrypi ? We are not using github for bug tracing and pull requests. Please check README for more info. Thanks for your support and I'm waiting for a Trello card.

**Comment by agherzan** [comment]
Did it for you. https://trello.com/c/EJ2MykE7/42-investigate-and-fix-if-needed-https-github-com-djwillis-meta-raspberrypi-issues-100

Please provide more info there.
