### ISSUE TITLE
how to include piTFT display driver for raspberrypi ?

### ISSUE THREAD

**Issue by abhi-84** [djwillis/meta-raspberrypi#102]
Sir
I need to include piTFT display driver to rpi-hwup-image? how to do it? please specify steps to do it....
please help

**Comment by texierp** [comment]
Hi, 

I plan to work on this issue as soon as possible (approximately  1 month).

**Comment by agherzan** [comment]
Thanks @texierp . Will wait for your feedback as I don't own a piTFT at this moment.

**Comment by agherzan** [comment]
As stated in README we are not using github - we are only keeping this as a mirror. Trello is the place where we trace and address issues and tasks. @texierp  @abhi-84 would you guys please create a trello card and follow up the progress there? https://trello.com/b/QsYeVjVe/meta-raspberrypi

Please provide feedback and switch this to Trello.

**Comment by texierp** [comment]
Hi @agherzan , It's ok for me, but I don't know how to create a trello card ...

**Comment by agherzan** [comment]
You just have to create a an account on trello and follow the link above. Everything else is as simple as.

**Comment by texierp** [comment]
Ok, but I don't have the permissions to create a trello card, it's normal ?

**Comment by agherzan** [comment]
GIve me your trello username.

**Comment by texierp** [comment]
Hi @agherzan, my trello username is : texierp (https://trello.com/texierp)

**Comment by agherzan** [comment]
Added! Thanks mate!
