### ISSUE TITLE
Enable Hard Float Support ?

### ISSUE THREAD

**Issue by andreabenini** [djwillis/meta-raspberrypi#104]
Hi guys,
I'd like to know if your layer could support armhf, if it supports it I'd like to know how to enable it, I'm currently generating armel binaries

**Comment by toolmmy** [comment]
As far as is can see it in the conf/machine/include/tune-arm1176jzf-s.inc file you can set your default tune to "arm1176jzfshf"
You can do this in your local.conf: 

conf/local.conf:
DEFAULTTUNE = "arm1176jzfshf"

our you can add a second machine configuration (e.g. raspberrypi-hf.conf).
Haven't tried it for my own so would be great if you could keep us in touch.

**Comment by agherzan** [comment]
Indeed. There is already a mailing list thread opened on this topic. Let's not have different threads for the same issue. As README states, we are using mailing lists for any discussions, so, let's follow up there.

Here is the ml thread link: https://lists.yoctoproject.org/pipermail/yocto/2015-January/022983.html

Thanks a lot for you support.
