### ISSUE TITLE
PREFERRED_PROVIDER_virtual/kernel

### ISSUE THREAD

**Issue by pficheux** [djwillis/meta-raspberrypi#105]
Hi,

I think it should be fine to use '?=' instead of '=' in conf/machine/include/rpi-default-providers.inc in order to allow overriding provider in local.conf (for example). I use it for Xenomai  kernel defined in meta-xenomai.

PREFERRED_PROVIDER_virtual/kernel ?= "linux-raspberrypi"

regards

**Comment by agherzan** [comment]
Hello,

Could you please submit an issue in the redmine issue tracker or using the mailing list? In this way multiple people will be able to help.

Thanks for understanding,
Andrei
