### ISSUE TITLE
Building for armhf (RaspberryPI on Debian)

### ISSUE THREAD

**Issue by mfortini** [djwillis/meta-raspberrypi#82]
I'm trying to build some OE deb packages using meta-raspberrypi, but my wheezy Raspbian distro is complaining that the OE .deb was built for the "arm" architecture and not for the "armhf" one.

Of course it would work on a non-accel Raspbian, but any improvement counts on a small ARM system

To fix this, I tried to use an "armhf" machine, by changing the machine definition in the following way. However, this didn't fix it, even if bitbake is telling me it's using the hardware accelerated FPU.

diff --git a/conf/machine/include/tune-arm1176jzf-s.inc b/conf/machine/include/tune-arm1176jzf-s.inc
index b52c161..9060f48 100644
--- a/conf/machine/include/tune-arm1176jzf-s.inc
+++ b/conf/machine/include/tune-arm1176jzf-s.inc
@@ -6,5 +6,5 @@ TUNEVALID[arm1176jzfs] = "Enable arm1176jzfs specific processor optimizations"
 TUNE_CCARGS += "${@bb.utils.contains("TUNE_FEATURES", "arm1176jzfs", "-mtune=arm1176jzf-s", "", d)}"

 AVAILTUNES += "arm1176jzfs"
-TUNE_FEATURES_tune-arm1176jzfs = "${TUNE_FEATURES_tune-armv6} arm1176jzfs"
-PACKAGE_EXTRA_ARCHS_tune-arm1176jzfs = "${PACKAGE_EXTRA_ARCHS_tune-armv6}"
+TUNE_FEATURES_tune-arm1176jzfs = "${TUNE_FEATURES_tune-armv6hf} arm1176jzfs"
+PACKAGE_EXTRA_ARCHS_tune-arm1176jzfs = "${PACKAGE_EXTRA_ARCHS_tune-armv6hf}"

**Comment by sherifomran** [comment]
@realglotzi i want to try changing the meta-raspberrypi to HF, can you please tell me how did you change it. Which value of Fine tune should it be? thank you
